# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b2386f8bfcc8cc49755a62d7107b354b4d4cd69f1a01e021e226a154aaae085fb0bd1e7579e3166964f148bfc8d58cd57076419c2489c9ae34fee0111d29385

test:
  secret_key_base: c89efe06d09b94ea5a2731d8499b10624eda46c38f1fd17723664103940d10bed329d420e6861c28483b516b63dc41e4656b04b6daa3f2e2c5b1aa0536c6b6db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
